[workspace]
members = [
    "crates/tagit-cfg",
    "crates/tagit-cfg-cargo",
    "crates/tagit-changelog",
    "crates/tagit-command",
    "crates/tagit-core",
    "crates/tagit-diff",
    "crates/tagit-impl",
    "crates/tagit-sub",
    "crates/tagit-sub-command",
    "crates/tagit-sub-core",
    "crates/tagit-sub-impl",
    "crates/tagit-tag",
    "crates/tagit-workspace",
    "crates/tagit-workspace-cargo",
    "crates/tagit-workspace-changelog",
    "crates/tagit-workspace-npm",
    "crates/tagit-workspace-pyproject",
    "xtask",
]

[workspace.package]
authors = ["Alisa Feistel <alisafeistel@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
repository = "https://github.com/parrrate/opentagit"
rust-version = "1.93.1"

[workspace.dependencies]
tagit-cfg = { version = "0.2.0", path = "crates/tagit-cfg" }
tagit-cfg-cargo = { version = "0.3.0", path = "crates/tagit-cfg-cargo" }
tagit-changelog = { version = "0.1.2", path = "crates/tagit-changelog" }
tagit-command = { version = "0.3.1", path = "crates/tagit-command" }
tagit-core = { version = "0.3.3", path = "crates/tagit-core" }
tagit-diff = { version = "0.1.4", path = "crates/tagit-diff" }
tagit-impl = { version = "0.3.4", path = "crates/tagit-impl" }
tagit-sub = { version = "0.1.0", path = "crates/tagit-sub" }
tagit-sub-command = { version = "0.1.0", path = "crates/tagit-sub-command" }
tagit-sub-core = { version = "0.1.0", path = "crates/tagit-sub-core" }
tagit-sub-impl = { version = "0.1.0", path = "crates/tagit-sub-impl" }
tagit-tag = { version = "0.3.3", path = "crates/tagit-tag" }
tagit-workspace = { version = "0.2.2", path = "crates/tagit-workspace" }
tagit-workspace-cargo = { version = "0.3.0", path = "crates/tagit-workspace-cargo" }
tagit-workspace-changelog = { version = "0.1.4", path = "crates/tagit-workspace-changelog" }
tagit-workspace-npm = { version = "0.2.0", path = "crates/tagit-workspace-npm" }
tagit-workspace-pyproject = { version = "0.2.0", path = "crates/tagit-workspace-pyproject" }

anyhow = "1.0.100"
cargo_metadata = "0.23.1"
chrono = "0.4.42"
clap = { version = "4.5.9", features = ["derive"] }
inventory = "0.3.21"
itertools = "0.14.0"
markdown = "1.0.0"
mdast_util_to_markdown = "0.0.2"
owo-colors = "4.2.3"
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", features = ["preserve_order"] }
static_assertions = "1.1.0"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.17"
toml = "0.9.7"

[package]
name = "tagit"
version = "0.0.0-a.1"
description = "collection of utilities used by tagit CLI tool internally"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
exclude = ["/.github", "/bin", "/.gitattribues", "/.gitignore", "/codegen.sh"]

[dependencies]
tagit-changelog.workspace = true
tagit-core.workspace = true
