[workspace]
members = [
    "crates/tagit-cfg",
    "crates/tagit-cfg-cargo",
    "crates/tagit-changelog",
    "crates/tagit-core",
    "crates/tagit-sub-command",
    "crates/tagit-sub-core",
    "crates/tagit-tag",
    "crates/tagit-workspace",
    "crates/tagit-workspace-cargo",
    "crates/tagit-workspace-changelog",
    "xtask",
]

[workspace.package]
authors = ["Alisa Feistel <alisafeistel@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
repository = "https://github.com/parrrate/opentagit"
rust-version = "1.90"

[workspace.dependencies]
tagit-cfg = { version = "0.1.0", path = "crates/tagit-cfg" }
tagit-cfg-cargo = { version = "0.1.0", path = "crates/tagit-cfg-cargo" }
tagit-changelog = { version = "0.1.0", path = "crates/tagit-changelog" }
tagit-core = { version = "0.3.2", path = "crates/tagit-core" }
tagit-sub-command = { version = "0.1.0", path = "crates/tagit-sub-command" }
tagit-sub-core = { version = "0.1.0", path = "crates/tagit-sub-core" }
tagit-workspace = { version = "0.1.4", path = "crates/tagit-workspace" }
tagit-workspace-cargo = { version = "0.1.1", path = "crates/tagit-workspace-cargo" }
tagit-workspace-changelog = { version = "0.1.2", path = "crates/tagit-workspace-changelog" }

anyhow = "1.0.100"
cargo = { version = "0.91.0" }
chrono = "0.4.42"
clap = { version = "4.5.9", features = ["derive"] }
inventory = "0.3.21"
markdown = "1.0.0"
mdast_util_to_markdown = "0.0.2"
owo-colors = "4.2.3"
semver = "1.0.23"
serde = { version = "1.0.228", features = ["derive"] }
static_assertions = "1.1.0"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.17"
toml = "0.9.7"

[package]
name = "tagit"
version = "0.0.0-a.1"
description = "collection of utilities used by tagit CLI tool internally"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
exclude = ["/.github", "/bin", "/.gitattribues", "/.gitignore", "/codegen.sh"]

[dependencies]
tagit-changelog.workspace = true
tagit-core.workspace = true
