[package]
name = "tagit-changelog-command"
version = "0.1.0"
description = "CLI arguments for `tagit changelog`"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
clap.workspace = true
