[package]
name = "tagit-workspace-cargo"
version = "0.1.3"
description = "tagit-workspace implementation for cargo"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tagit-cfg.workspace = true
tagit-cfg-cargo.workspace = true
tagit-core.workspace = true
tagit-workspace.workspace = true

anyhow.workspace = true
blake3 = { version = "1.6.0", features = ["pure"], optional = true }
cargo.workspace = true
semver.workspace = true

[features]
static = ["dep:blake3", "cargo/all-static"]
