[package]
name = "tagit-workspace-cargo"
version = "0.1.0"
description = "tagit-workspace implementation for cargo"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tagit-cfg.workspace = true
tagit-cfg-cargo.workspace = true
tagit-workspace.workspace = true

anyhow.workspace = true
cargo.workspace = true
semver.workspace = true
